### ISSUE TITLE
Cross-crate flamegraph

### ISSUE THREAD

**Issue by sharksforarms** [TyOverby/flame#37] opened 2018-05-10 12:45 UTC
Hello, I'm trying to use this across multiple crates, is this possible?

**Comment by TyOverby** [comment] 2018-05-10 17:42
Yes; if both crates have the same `flame` version, then everything should work out.

**Comment by sharksforarms** [comment] 2018-05-11 23:25
Ok so I narrowed it down to using feature flags:

https://github.com/sharksforarms/testflame

`cargo +nightly run --all-features flame_it`

Doesn't seem to work well when feature-guarding it

**Comment by TyOverby** [comment] 2018-05-12 00:57
Your repo only has a readme file in it.  Can you publish again?

**Comment by sharksforarms** [comment] 2018-05-12 01:01
Done

**Comment by TyOverby** [comment] 2018-05-12 01:17
I think that the problem is that [this line](https://github.com/sharksforarms/testflame/blob/c32dd82643c892a8a7695be88be2ec4787002d7e/Cargo.toml#L12) where you import your subcrate needs to enable it's own feature.

the features that are both named `flame_it` are not the same between crates.

**Comment by sharksforarms** [comment] 2018-05-12 01:28
Right, I changed it to this
`myothercrate = { path = "./myothercrate", features = ["flame_it"] }`

And it works. But now that means that myothercrate is always enabling the `flame_it` feature

**Comment by TyOverby** [comment] 2018-05-12 21:26
oh nice!  Yeah, I gotta say I've never used features beyond the most trivial.  

Looks like I can close this for now; if you run into anything else feel free to re-open or make a new issue!

**Closed by TyOverby** 2018-05-12 21:26 UTC
